# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/erikg',
                'doc_host': 'https://erikgaas.github.io',
                'git_url': 'https://github.com/erikgaas/erikg',
                'lib_path': 'erikg'},
  'syms': {'erikg.core': {'erikg.core.foo': ('core.html#foo', 'erikg/core.py')}}}
